---
- name: install httpd
  hosts: all
  gather_facts: no
  vars:    
      ansible_python_interpreter: auto
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
    - name: show distribution
      debug:
        msg: "{{ ansible_distribution }}"
 
